services:
  - docker:dind

unit-test:
  stage: test
  image:
    name: maven:3.6.3-jdk-11-slim
  only:
    changes:
      - pom.xml
      - src/*
  script:
    - mvn verify
  artifacts:
    paths: [target/failsafe-reports/TEST-*.xml]
    when: always
    expire_in: one week
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml
  allow_failure: false