services:
  - docker:dind

sec-dast_baseline:
  stage: sec-release
  image:
    name: owasp/zap2docker-weekly
  before_script:
    - mkdir /zap/wrk
  script:
    - zap-baseline.py -t https://hapi.f5labs.dev/fhir -I -J dast_baseline_scan-results.json
  after_script:
    - mv /zap/wrk/dast_baseline_scan-results.json /builds/shainsingh/hapi-fhir/
  rules:
    - if: $scan_periodic != "nightly"
      when: always
  artifacts:
    paths: [dast_baseline_scan-results.json]
    when: always
    expire_in: one week
  allow_failure: true

sec-dast_full:
  stage: sec-release
  image:
    name: owasp/zap2docker-weekly
  before_script:
    - mkdir /zap/wrk
  script:
    - zap-full-scan.py -t https://hapi.f5labs.dev/fhir -I -J dast_full_scan-results.json
  after_script:
    - mv /zap/wrk/dast_full_scan-results.json /builds/shainsingh/hapi-fhir/
  rules:
    - if: $scan_periodic == "nightly"
      when: always
  artifacts:
    paths: [dast_full_scan-results.json]
    when: always
    expire_in: one week
  allow_failure: true
